### PR TITLE
Minor changes to the biomodels qualifiers

### PR DESCRIPTION
**Pull request by nickerso**
Changes suggested at HARMONY 2023, mostly from @jhgennari.

### CODE REVIEW

**Review by matthiaskoenig — CHANGES_REQUESTED** [review]
This is a major change in my opinion and should be versioned (because the identifiers change). I.e. I would strongly suggest to create a new version of the miriam qualifiers and give a version 1.0 for the old document. I.e. add the changes as a 1.1 document. 
Current libraries and tools such as libsbml implement basically 1.0 at the moment and would break with the changes (or not support 1.1).

**Comment by jhgennari** [comment]
Matthias: It's isn't our intent to change *any* of the identifiers with this change. Do you mean removing the "noun" versions? I thought those weren't used. We have added 5 new identifiers.

**Comment by matthiaskoenig** [comment]
You are adding new identifiers in addition, e.g., `hasSource`, `hasSink`, `hasMultiplier` as far as I can tell.
Addition of identifiers will break existing implementations such as in libsbml which have hardcoded enums for the existing identifiers.
See for instance also here:
https://github.com/matthiaskoenig/pymetadata/blob/develop/src/pymetadata/identifiers/miriam.py
COPASI also has this hardcoded and many other tools.

I highly recommend versioning this and clearly stating version 1.1 adds the following 5 identifiers.

**Comment by matthiaskoenig** [comment]
I am fine with updating the identifiers, I just want to have a version for the old definition and the new definition with the additional identifiers. I can do this tomorrow if you are fine with this. I.e. adding the version 1.0 and 1.1 of the identifiers to the specifications.

**Comment by jhgennari** [comment]
Ok, sounds good. Yes, we are proposing adding 5 new qualifiers. (in addition to the 3 you list, there is "hasMultiplier" and "hasPhysicalEntity"). Hopefully, it won't be too hard to update libSBML to allow for these.

**Comment by matthiaskoenig** [comment]
No the update should be pretty easy. The main problem is that most tools just map everything they don't understand to UNKNOWN, i.e. the new identifiers would just be dropped by most tools at the moment.

**Comment by nickerso** [comment]
@matthiaskoenig @jhgennari - I've moved the proposed changes to a qualifiers 1.1. I have not moved the current qualifiers to a `version 1.0` other than to note in the new version that the previous version is 1.0.

**Review by matthiaskoenig — APPROVED** [review]

**Comment by matthiaskoenig** [comment]
I will make the remaining changes in the repository.

**Pull request merged**
